export type ErrorCode =
  | "AUTH_REQUIRED"
  | "PERMISSION_DENIED"
  | "MODULE_DISABLED"
  | "MODULE_UNAVAILABLE"
  | "VALIDATION_FAILED"
  | "DEPENDENCY_UNAVAILABLE"
  | "AI_UNAVAILABLE"
  | "DATA_CONFLICT"
  | "INTERNAL_ERROR";
