export type UserRole = "admin" | "manager" | "editor" | "operator" | "viewer";

export const ALL_PERMISSIONS = [
  "modules.read",
  "modules.manage",
  "tasks.read",
  "tasks.create",
  "tasks.update",
  "tasks.assign",
  "tasks.transition",
  "tasks.archive",
  "tasks.manage",
  "agent.use",
  "agent.tools.read",
  "audit.read",
  "documents.read",
  "documents.create",
  "documents.update",
  "documents.delete",
  "documents.manage",
] as const;

export type Permission = (typeof ALL_PERMISSIONS)[number];

export const ROLE_PERMISSIONS: Record<UserRole, readonly Permission[]> = {
  admin: [
    "modules.read",
    "modules.manage",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.transition",
    "tasks.archive",
    "tasks.manage",
    "agent.use",
    "agent.tools.read",
    "audit.read",
    "documents.read",
    "documents.create",
    "documents.update",
    "documents.delete",
    "documents.manage",
  ],
  manager: [
    "modules.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.transition",
    "tasks.archive",
    "agent.use",
    "agent.tools.read",
    "documents.read",
    "documents.create",
    "documents.update",
    "documents.delete",
  ],
  editor: [
    "modules.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.assign",
    "tasks.transition",
    "agent.use",
    "documents.read",
    "documents.create",
    "documents.update",
  ],
  operator: [
    "modules.read",
    "tasks.read",
    "tasks.create",
    "tasks.update",
    "tasks.transition",
    "documents.read",
    "documents.create",
    "documents.update",
  ],
  viewer: [
    "modules.read",
    "documents.read",
  ],
};
